#isme phelys instrucetion de diye janegy ki ye ye kam ahi bas


name: Frontend CI

on:
push:
branches: [main]

jobs:
frontend:
runs-on: ubuntu-latest

steps:
  - name: Get code
    uses: actions/checkout@v4

  - name: Setup Node
    uses: actions/setup-node@v4
    with:
      node-version: 22

  - name: Install dependencies
    working-directory: frontend/my-app
    run: npm ci

  - name: Build frontend
    working-directory: frontend/my-app
    run: npm run build